Bash -> Posix Shell

diff --git a/mkRCID b/mkRCID
--- a/mkRCID
+++ b/mkRCID
@@ -1,146 +1,115 @@
-#!/bin/bash
-set -e
-#set -x
+#!/bin/sh
+set -e      # Abort upon error
+#set -x     # Print every command
 
 #######################################
-#	Create new identity in Roundcube
-#		mkRCID user_name new_alias
-#
-#	Arguments:
-#		username (string): user's standard e-mail
-#		new_alias (string): user's new alias
-#	Returns:
-#		0 upon success
-#		>=1 upon error
+#   Description:
+#       Create new identity in Roundcube
+#   Usage:
+#       ./mkRCID user_name new_alias
+#   Arguments:
+#        user_name (string): user's main address
+#        new_alias (string): user's new alias
+#   Returns:
+#       0 upon success
+#       >=1 upon error
 #######################################
-function main() {
-	local readonly USAGE="Usage: mkRCID user_name [new_alias]"
+main() {
+    # Check if $USAGE is respected
+    readonly USAGE='Usage: ./mkRCID user_name new_alias'
+    [ "$#" -lt 1 ] && err "Error: 2 argument(s) expected, $# received" && err "$USAGE" && return 1
+    [ ! -f .env ] && err "Error: could not find .env file" && return 2
 
-	if [[ "${#}" -lt 1 ]] || [[ "${#}" -gt 2 ]]; then
-		err "Error: one or two arguments expected, ${#} received"
-		err "${USAGE}"
-		return 1
-	fi
+     # Load .env
+    set -a; . ./.env; set +a
 
-	local readonly user_name="${1}"
-	local readonly new_alias="${2}"
+    # Parameters
+    readonly user_name="$1"
+    readonly new_alias="$2"
 
-	if [[ ! -f .env ]]; then
-		err "Error: could not find .env file"
-		return 2
-	fi
+    # Check if identity already exists
+    check_duplicates
 
-	# Load .env
-	set -o allexport && source .env && set +o allexport
+    # Display existing identities
+    readonly user_id="$(get_user_id "$user_name")"
+	show_IDs
 
-	check_duplicates "${new_alias}"					# Check if identity already exists
-	local readonly user_id=$(get_user_id "${user_name}")		# Find user_id
-	show_IDs "${user_name}" "${user_id}"				# Display existing identities
-
-	[[ ! -z "${new_alias}" ]] && insert_new "${new_alias}" "${user_id}"	# Create the RCID
-
-	return 0
+    # Create the RCID, if alias is provided
+	[ ! -z "$new_alias" ] && insert_new
 }
 
 #######################################
-#	Check in identities
-#	if the alias is already there
+#   Check in identities if the alias is already there
 #######################################
-function check_duplicates() {
-	[[ "${#}" -ne 1 ]] && return 1
-	local readonly new_alias="${1}"
-
+check_duplicates() {
 	# Check if identity already exists
-	local readonly check_identity=$( \
+	readonly check_identity="$( \
 		mysql --skip-column-names \
-			--user="${CONFIG_USER}" --password="${CONFIG_PASSWORD}" --database="${CONFIG_DATABASE}" \
-			--execute="SELECT * FROM identities WHERE email='${new_alias}'" \
-	)
+			--user="$CONFIG_USER" --password="$CONFIG_PASSWORD" --database="$CONFIG_DATABASE" \
+			--execute="SELECT * FROM identities WHERE email='$new_alias'" \
+	)"
 
-	if [[ ! -z "${check_identity}" ]]; then
-		err "Error: identity with alias '${new_alias}' already exists:"
-		echo "${check_identity}"
-		return 4
-	fi
-
-	return 0
+    [ ! -z "$check_identity" ] \
+		&& err "Error: identity with alias '$new_alias' already exists" \
+        && return 3 \
+		|| return 0
 }
 
 #######################################
 #	Fetch user_id from users
 #######################################
-function get_user_id() {
-	[[ "${#}" -ne 1 ]] && return 1
-	local readonly user_name="${1}"
-
-	local readonly user_id=$( \
+get_user_id() {
+	readonly user_id="$( \
 		mysql --skip-column-names \
-			--user="${CONFIG_USER}" --password="${CONFIG_PASSWORD}" --database="${CONFIG_DATABASE}" \
-			--execute="SELECT user_id FROM users WHERE username='${user_name}'" \
-	)
+			--user="$CONFIG_USER" --password="$CONFIG_PASSWORD" --database="$CONFIG_DATABASE" \
+			--execute="SELECT user_id FROM users WHERE username='$user_name'" \
+	)"
 
-	if [[ -z "${user_id}" ]]; then
-		err "Error: user '${user_name}' not found"
-		return 5
-	fi
+    [ -z "$user_id" ] \
+        && err "Error: user '$user_name' not found" \
+        && return 4
 
-	echo "${user_id}"
-
-	return 0
+	echo "$user_id"
 }
 
 #######################################
 #	Display existing IDs
 #######################################
-function show_IDs() {
-	[[ "${#}" -ne 2 ]] && return 1
-	local readonly user_name="${1}"
-	local readonly user_id="${2}"
-
-	mysql --user="${CONFIG_USER}" --password="${CONFIG_PASSWORD}" --database="${CONFIG_DATABASE}" \
-		--execute="SELECT standard, email FROM identities WHERE user_id='${user_id}'"
-
-	return 0
+show_IDs() {
+	mysql --user="$CONFIG_USER" --password="$CONFIG_PASSWORD" --database="$CONFIG_DATABASE" \
+		--execute="SELECT standard, email FROM identities WHERE user_id='$user_id'"
 }
 
 #######################################
 #	Insert new ID
 #######################################
-function insert_new() {
-	[[ "${#}" -ne 2 ]] && return 1
-	local readonly new_alias="${1}"
-	local readonly user_id="${2}"
-
-	warn "\nFound the above existing identities.\nProceed and create '${new_alias}'?"
+insert_new() {
+	warn "Found the above existing identities. Proceed and create '$new_alias'?"
 
 	# Create new identity
-	echo -e "\nAdding new identity..."
+	printf "\nAdding new identity...\n"
 
-	mysql --user="${CONFIG_USER}" --password="${CONFIG_PASSWORD}" --database="${CONFIG_DATABASE}" \
+	mysql --user="$CONFIG_USER" --password="$CONFIG_PASSWORD" --database="$CONFIG_DATABASE" \
 		--execute="\
 			INSERT INTO \
 				\`identities\` (\`identity_id\`, \`user_id\`, \`changed\`, \`del\`, \`standard\`, \`name\`, \`organization\`, \`email\`, \`reply-to\`, \`bcc\`, \`signature\`, \`html_signature\`) \
-			VALUES (NULL, '${user_id}', NOW(), 0, 0, '', '', '${new_alias}', '', '', NULL, 0) \
+			VALUES (NULL, '$user_id', NOW(), 0, 0, '', '', '$new_alias', '', '', NULL, 0) \
 		"
-
-	return 0
-}
-
-#######################################
-#	Print error message to stderr
-#	https://google.github.io/styleguide/shellguide.html
-#######################################
-function err() {
-	echo [2021-09-10T11:32:07+0200]: "${*}" >&2
 }
 
 #######################################
 #	Warn user and ask for confirmation
 #######################################
-function warn() {
-	echo -e "${*}"
-	echo -n "Press any key to continue or ^C to abort."
-	read -s -n 1 key
+warn() {
+	printf "\n%s\n" "$*"
+	read -p "Press any key to continue or ^C to abort." key
 }
 
-main "${@}"; exit
+#######################################
+#   Print error message to stderr
+#   https://google.github.io/styleguide/shellguide.html
+#######################################
+err() { echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2; }
+
+main "$@"; exit
+
